name: bmk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  fluttertoast: ^8.2.8
  gap: ^3.0.1
  go_router: ^14.6.2
  hooks_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.5
  pub_semver: ^2.1.4
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  flutter_staggered_grid_view: ^0.7.0
  any_link_preview: ^3.0.2
  cached_network_image: ^3.4.1
  receive_sharing_intent: ^1.8.1
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  lints: ^5.0.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.9.0
  drift_dev: ^2.22.1
  flutter_launcher_icons: ^0.14.2

flutter:
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/src/common/constants/gen/

flutter_native_splash:
  color: "#9b3cfd"
  image: assets/images/bmk.png
  color_dark: "#9b3cfd"
  android_12:
    color: "#9b3cfd"
    icon_background_color: "#9b3cfd"
    image: assets/images/bmk.png
